# Generated by Django 3.2.5 on 2022-10-25 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='user_info_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=14)),
                ('age', models.CharField(blank=True, max_length=5)),
                ('sex', models.CharField(blank=True, max_length=10)),
                ('background_img', models.ImageField(blank=True, upload_to='background_img/%Y%m%d/')),
                ('portrait', models.ImageField(blank=True, upload_to='portrait/%Y%m%d/')),
                ('self_introduce', models.TextField(blank=True, max_length=500)),
                ('signature', models.TextField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
